"""Generate Python constants from the naming registry.

Usage::

    python registry/generate_registry.py

Reads ``registry/naming_registry.json`` and writes
``src/voice/core/registry_constants.py``.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = ROOT / "registry" / "naming_registry.json"
OUTPUT_PATH = ROOT / "src" / "voice" / "core" / "registry_constants.py"

HEADER = '''\
"""Auto-generated registry constants — DO NOT EDIT.

Generated by ``registry/generate_registry.py`` from
``registry/naming_registry.json``.
"""

from __future__ import annotations

'''


def _make_constant_name(section: str, key: str) -> str:
    return f"{section.upper()}_{key.upper()}_LABEL"


def generate() -> str:
    with REGISTRY_PATH.open() as f:
        registry: dict = json.load(f)

    lines = [HEADER]

    for section_name, entries in registry.items():
        lines.append(f"# ── {section_name} {'─' * (60 - len(section_name))}\n")
        for key, meta in entries.items():
            const = _make_constant_name(section_name, key)
            label = meta["label"]
            lines.append(f'{const} = "{label}"\n')
        lines.append("\n")

    return "".join(lines)


def main() -> None:
    content = generate()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
