"""Generate Python constants from the naming registry.

Usage::

    python registry/generate_registry.py

Reads ``registry/naming_registry.json`` and writes
``backend/src/ekko/core/registry_constants.py``.

Example usage::

    # Using label constants (for display)
    from ekko.core.registry_constants import MESSAGE_ROLES_USER_LABEL
    print(f"Role: {MESSAGE_ROLES_USER_LABEL}")  # "User"

    # Using value constants (for dict keys, API fields)
    from ekko.core.registry_constants import FIELD_ROLE, FIELD_CONTENT
    message = {FIELD_ROLE: "user", FIELD_CONTENT: "Hello"}

    # Using route constants
    from ekko.core.registry_constants import ROUTE_HEALTH, ROUTE_GRAPHQL
    app.add_route(ROUTE_HEALTH, health_handler)
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = ROOT / "registry" / "naming_registry.json"
OUTPUT_PATH = ROOT / "backend" / "src" / "ekko" / "core" / "registry_constants.py"

HEADER = '''\
"""Auto-generated registry constants — DO NOT EDIT.

Generated by ``registry/generate_registry.py`` from
``registry/naming_registry.json``.

Usage examples::

    # Label constants (for display)
    from ekko.core.registry_constants import MESSAGE_ROLES_USER_LABEL
    print(f"Role: {MESSAGE_ROLES_USER_LABEL}")  # "User"

    # Field name constants (for dict keys)
    from ekko.core.registry_constants import FIELD_ROLE, FIELD_CONTENT
    message = {FIELD_ROLE: "user", FIELD_CONTENT: "Hello"}

    # Route constants (for API paths)
    from ekko.core.registry_constants import ROUTE_HEALTH, ROUTE_GRAPHQL
    app.add_route(ROUTE_HEALTH, health_handler)

    # Error code constants
    from ekko.core.registry_constants import ERROR_VALUE_ERROR_MISSING
    raise ValueError(ERROR_VALUE_ERROR_MISSING)

    # Status value constants
    from ekko.core.registry_constants import STATUS_ACTIVE
    user.status = STATUS_ACTIVE
"""

from __future__ import annotations

'''


def _make_constant_name(section: str, key: str, suffix: str = "LABEL") -> str:
    """Generate constant name with section-specific prefix."""
    # Use semantic prefixes for new sections
    if section == "field_names":
        return f"FIELD_{key.upper()}"
    elif section == "api_routes":
        return f"ROUTE_{key.upper()}"
    elif section == "error_codes":
        return f"ERROR_{key.upper()}"
    elif section == "status_values":
        return f"STATUS_{key.upper()}"
    else:
        # Legacy format for existing sections
        return f"{section.upper()}_{key.upper()}_{suffix}"


def generate() -> str:
    with REGISTRY_PATH.open() as f:
        registry: dict = json.load(f)

    lines = [HEADER]

    for section_name, entries in registry.items():
        lines.append(f"# ── {section_name} {'─' * (60 - len(section_name))}\n")
        for key, meta in entries.items():
            # Determine which field to export (label or value)
            if "value" in meta:
                const = _make_constant_name(section_name, key, "VALUE")
                value = meta["value"]
                lines.append(f'{const} = "{value}"\n')
            if "label" in meta:
                const = _make_constant_name(section_name, key, "LABEL")
                label = meta["label"]
                lines.append(f'{const} = "{label}"\n')
        lines.append("\n")

    return "".join(lines)


def main() -> None:
    content = generate()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
