services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      target: prod
    environment:
      EKKO_ENVIRONMENT: prod
    restart: unless-stopped
    networks:
      - backend

  caddy:
    build:
      context: ./caddy
      dockerfile: Containerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
