"""Auto-generated registry constants — DO NOT EDIT.

Generated by ``registry/generate_registry.py`` from
``registry/naming_registry.json``.
"""

from __future__ import annotations

# ── environments ────────────────────────────────────────────────
ENVIRONMENTS_LOCAL_LABEL = "Local"
ENVIRONMENTS_DEV_LABEL = "Development"
ENVIRONMENTS_TEST_LABEL = "Test"
ENVIRONMENTS_STAGING_LABEL = "Staging"
ENVIRONMENTS_PROD_LABEL = "Production"

# ── llm_providers ───────────────────────────────────────────────
LLM_PROVIDERS_OPENAI_LABEL = "OpenAI"
LLM_PROVIDERS_AZURE_OPENAI_LABEL = "Azure OpenAI"
LLM_PROVIDERS_ANTHROPIC_LABEL = "Anthropic"
LLM_PROVIDERS_COHERE_LABEL = "Cohere"
LLM_PROVIDERS_GOOGLE_LABEL = "Google"
LLM_PROVIDERS_OTHER_LABEL = "Other"

# ── stt_providers ───────────────────────────────────────────────
STT_PROVIDERS_WHISPER_LABEL = "Whisper"
STT_PROVIDERS_FASTER_WHISPER_LABEL = "Faster Whisper"
STT_PROVIDERS_AZURE_SPEECH_LABEL = "Azure Speech"
STT_PROVIDERS_GOOGLE_SPEECH_LABEL = "Google Speech"
STT_PROVIDERS_OTHER_LABEL = "Other"

# ── audio_formats ───────────────────────────────────────────────
AUDIO_FORMATS_WAV_LABEL = "WAV"
AUDIO_FORMATS_FLAC_LABEL = "FLAC"
AUDIO_FORMATS_MP3_LABEL = "MP3"
AUDIO_FORMATS_OGG_LABEL = "OGG"
AUDIO_FORMATS_PCM16_LABEL = "PCM 16-bit"

# ── message_roles ───────────────────────────────────────────────
MESSAGE_ROLES_SYSTEM_LABEL = "System"
MESSAGE_ROLES_USER_LABEL = "User"
MESSAGE_ROLES_ASSISTANT_LABEL = "Assistant"
MESSAGE_ROLES_TOOL_LABEL = "Tool"

# ── transcript_statuses ─────────────────────────────────────────
TRANSCRIPT_STATUSES_RECEIVED_LABEL = "Received"
TRANSCRIPT_STATUSES_QUEUED_LABEL = "Queued"
TRANSCRIPT_STATUSES_PROCESSING_LABEL = "Processing"
TRANSCRIPT_STATUSES_COMPLETED_LABEL = "Completed"
TRANSCRIPT_STATUSES_FAILED_LABEL = "Failed"
TRANSCRIPT_STATUSES_CANCELLED_LABEL = "Cancelled"
