"""Auto-generated registry constants — DO NOT EDIT.

Generated by ``registry/generate_registry.py`` from
``registry/naming_registry.json``.

Usage examples::

    # Label constants (for display)
    from ekko.core.registry_constants import MESSAGE_ROLES_USER_LABEL
    print(f"Role: {MESSAGE_ROLES_USER_LABEL}")  # "User"

    # Field name constants (for dict keys)
    from ekko.core.registry_constants import FIELD_ROLE, FIELD_CONTENT
    message = {FIELD_ROLE: "user", FIELD_CONTENT: "Hello"}

    # Route constants (for API paths)
    from ekko.core.registry_constants import ROUTE_HEALTH, ROUTE_GRAPHQL
    app.add_route(ROUTE_HEALTH, health_handler)

    # Error code constants
    from ekko.core.registry_constants import ERROR_VALUE_ERROR_MISSING
    raise ValueError(ERROR_VALUE_ERROR_MISSING)

    # Status value constants
    from ekko.core.registry_constants import STATUS_ACTIVE
    user.status = STATUS_ACTIVE
"""

from __future__ import annotations

# ── environments ────────────────────────────────────────────────
ENVIRONMENTS_LOCAL_LABEL = "Local"
ENVIRONMENTS_DEV_LABEL = "Development"
ENVIRONMENTS_TEST_LABEL = "Test"
ENVIRONMENTS_STAGING_LABEL = "Staging"
ENVIRONMENTS_PROD_LABEL = "Production"

# ── llm_providers ───────────────────────────────────────────────
LLM_PROVIDERS_OPENAI_LABEL = "OpenAI"
LLM_PROVIDERS_AZURE_OPENAI_LABEL = "Azure OpenAI"
LLM_PROVIDERS_ANTHROPIC_LABEL = "Anthropic"
LLM_PROVIDERS_COHERE_LABEL = "Cohere"
LLM_PROVIDERS_GOOGLE_LABEL = "Google"
LLM_PROVIDERS_OTHER_LABEL = "Other"

# ── stt_providers ───────────────────────────────────────────────
STT_PROVIDERS_WHISPER_LABEL = "Whisper"
STT_PROVIDERS_FASTER_WHISPER_LABEL = "Faster Whisper"
STT_PROVIDERS_AZURE_SPEECH_LABEL = "Azure Speech"
STT_PROVIDERS_GOOGLE_SPEECH_LABEL = "Google Speech"
STT_PROVIDERS_OTHER_LABEL = "Other"

# ── audio_formats ───────────────────────────────────────────────
AUDIO_FORMATS_WAV_LABEL = "WAV"
AUDIO_FORMATS_FLAC_LABEL = "FLAC"
AUDIO_FORMATS_MP3_LABEL = "MP3"
AUDIO_FORMATS_OGG_LABEL = "OGG"
AUDIO_FORMATS_PCM16_LABEL = "PCM 16-bit"

# ── message_roles ───────────────────────────────────────────────
MESSAGE_ROLES_SYSTEM_LABEL = "System"
MESSAGE_ROLES_USER_LABEL = "User"
MESSAGE_ROLES_ASSISTANT_LABEL = "Assistant"
MESSAGE_ROLES_TOOL_LABEL = "Tool"

# ── transcript_statuses ─────────────────────────────────────────
TRANSCRIPT_STATUSES_RECEIVED_LABEL = "Received"
TRANSCRIPT_STATUSES_QUEUED_LABEL = "Queued"
TRANSCRIPT_STATUSES_PROCESSING_LABEL = "Processing"
TRANSCRIPT_STATUSES_COMPLETED_LABEL = "Completed"
TRANSCRIPT_STATUSES_FAILED_LABEL = "Failed"
TRANSCRIPT_STATUSES_CANCELLED_LABEL = "Cancelled"

# ── field_names ─────────────────────────────────────────────────
FIELD_ROLE = "role"
FIELD_CONTENT = "content"
FIELD_EMAIL = "email"
FIELD_NAME = "name"
FIELD_TYPE = "type"
FIELD_REQUEST_ID = "request_id"
FIELD_USER = "user"

# ── api_routes ──────────────────────────────────────────────────
ROUTE_HEALTH = "/health"
ROUTE_DOCS = "/docs"
ROUTE_OPENAPI_JSON = "/openapi.json"
ROUTE_REDOC = "/redoc"
ROUTE_GRAPHQL = "/graphql"
ROUTE_START_STREAM = "/start_stream"
ROUTE_PAUSE_STREAM = "/pause_stream"

# ── error_codes ─────────────────────────────────────────────────
ERROR_VALUE_ERROR_MISSING = "value_error.missing"

# ── status_values ───────────────────────────────────────────────
STATUS_ACTIVE = "active"
